server:
  port: 9001
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: system-server
          uri: lb://SYSTEM-SERVER
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  security:
    user:
      name: admin
      password: 123456
      roles: ADMIN
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    eureka-server-port: 9000
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug